name: Bug Report
description: Report a bug or issue with the build system
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: When I run X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. See error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - autobuild script
        - merge-debian-raspios script
        - QEMU setup
        - Image configuration
        - GitHub Actions CI/CD
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: image
    attributes:
      label: Image Configuration
      description: Which image were you building?
      placeholder: exemple

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your build environment
      value: |
        - OS:
        - Kernel:
        - RaspiOS version:
        - Debian version:
        - Script version/commit:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste relevant error messages or log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested with the latest version from main branch
          required: true